# Generated by Django 6.0 on 2025-12-21 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_scans', models.IntegerField(default=0, help_text='总扫描次数')),
                ('vulnerabilities_found', models.IntegerField(default=0, help_text='发现的漏洞总数')),
                ('critical_vulnerabilities', models.IntegerField(default=0, help_text='危急漏洞数量')),
                ('active_tasks', models.IntegerField(default=0, help_text='活跃任务数量')),
                ('system_uptime_hours', models.FloatField(default=0.0, help_text='系统运行时间（小时）')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, help_text='最后更新时间')),
            ],
            options={
                'verbose_name': '系统统计',
                'verbose_name_plural': '系统统计',
            },
        ),
    ]
