/**
 * LabHome - 漏洞实验室首页
 * 
 * 展示漏洞场景列表，支持按类型和难度筛选。
 */

import React, { useState, useEffect } from 'react';
import { api } from '../api';

// 漏洞类型映射
const VULN_TYPE_NAMES: Record<string, string> = {
  SQLI: 'SQL注入',
  XSS_REFLECTED: '反射型XSS',
  XSS_STORED: '存储型XSS',
  CMD_INJECTION: '命令注入',
  LFI: '本地文件包含',
  RFI: '远程文件包含',
  SSRF: '服务端请求伪造',
  XXE: 'XXE注入',
  PATH_TRAVERSAL: '路径穿越',
  INFO_DISCLOSURE: '信息泄露',
  OPEN_REDIRECT: '开放重定向',
  CSRF: 'CSRF',
};

// 难度颜色映射
const DIFFICULTY_COLORS: Record<string, string> = {
  easy: 'bg-green-100 text-green-700 border-green-200',
  medium: 'bg-yellow-100 text-yellow-700 border-yellow-200',
  hard: 'bg-red-100 text-red-700 border-red-200',
};

// 难度中文名
const DIFFICULTY_NAMES: Record<string, string> = {
  easy: '初级',
  medium: '中级',
  hard: '高级',
};

// 漏洞类型颜色
const VULN_TYPE_COLORS: Record<string, string> = {
  SQLI: 'bg-blue-100 text-blue-700 border-blue-200',
  XSS_REFLECTED: 'bg-orange-100 text-orange-700 border-orange-200',
  XSS_STORED: 'bg-orange-100 text-orange-700 border-orange-200',
  CMD_INJECTION: 'bg-red-100 text-red-700 border-red-200',
  LFI: 'bg-purple-100 text-purple-700 border-purple-200',
  RFI: 'bg-purple-100 text-purple-700 border-purple-200',
  SSRF: 'bg-pink-100 text-pink-700 border-pink-200',
  XXE: 'bg-indigo-100 text-indigo-700 border-indigo-200',
  PATH_TRAVERSAL: 'bg-teal-100 text-teal-700 border-teal-200',
  INFO_DISCLOSURE: 'bg-gray-100 text-gray-700 border-gray-200',
  OPEN_REDIRECT: 'bg-cyan-100 text-cyan-700 border-cyan-200',
  CSRF: 'bg-amber-100 text-amber-700 border-amber-200',
};

interface AttackStep {
  step: number;
  title: string;
  description?: string;
  request?: Record<string, unknown>;
  response?: Record<string, unknown>;
  payload?: string;
  payload_explanation?: string;
  result?: string;
}

interface Remediation {
  title: string;
  description?: string;
  code?: string;
  language?: string;
}

interface Learning {
  principle?: string;
  cwe?: string;
  owasp?: string;
  impact?: string;
  references?: string[];
}

interface LabScenario {
  id: number;
  name: string;
  vuln_type: string;
  difficulty: string;
  description?: string;
  attack_steps: AttackStep[];
  remediation: Remediation[];
  learning: Learning;
  tags: string[];
  is_active: boolean;
  is_auto_generated?: boolean;
  source_scan_task_id?: number;
  created_at?: string;
  updated_at?: string;
}

interface LabScenarioListResponse {
  items: LabScenario[];
  total: number;
}

interface VulnTypeInfo {
  code: string;
  name: string;
  count: number;
}

const LabHome: React.FC = () => {
  const [scenarios, setScenarios] = useState<LabScenario[]>([]);
  const [vulnTypes, setVulnTypes] = useState<VulnTypeInfo[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedType, setSelectedType] = useState<string | null>(null);
  const [selectedDifficulty, setSelectedDifficulty] = useState<string | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [showAutoGenerated, setShowAutoGenerated] = useState<boolean | null>(null);
  const [selectedScenario, setSelectedScenario] = useState<LabScenario | null>(null);
  const [currentStep, setCurrentStep] = useState(0);
  const [activeTab, setActiveTab] = useState<'attack' | 'remediation' | 'learning'>('attack');

  // 加载场景列表
  const loadScenarios = async () => {
    setLoading(true);
    try {
      const response = await api.getLabScenarios({
        vuln_type: selectedType || undefined,
        difficulty: selectedDifficulty || undefined,
        search: searchQuery || undefined,
      });
      setScenarios(response.items);
    } catch (error) {
      console.error('加载场景失败:', error);
    } finally {
      setLoading(false);
    }
  };

  // 加载漏洞类型
  const loadVulnTypes = async () => {
    try {
      const response = await api.getLabVulnTypes();
      setVulnTypes(response);
    } catch (error) {
      console.error('加载漏洞类型失败:', error);
    }
  };

  useEffect(() => {
    loadVulnTypes();
  }, []);

  useEffect(() => {
    loadScenarios();
  }, [selectedType, selectedDifficulty, searchQuery]);

  // 重置筛选
  const handleResetFilters = () => {
    setSelectedType(null);
    setSelectedDifficulty(null);
    setSearchQuery('');
    setShowAutoGenerated(null);
  };

  // 返回列表
  const handleBackToList = () => {
    setSelectedScenario(null);
    setCurrentStep(0);
    setActiveTab('attack');
  };

  // 场景列表视图
  if (selectedScenario) {
    return (
      <div className="p-6">
        {/* 头部 */}
        <div className="mb-6">
          <button
            onClick={handleBackToList}
            className="flex items-center gap-2 text-awvs-text-secondary hover:text-awvs-primary transition-colors mb-4"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            返回场景列表
          </button>

          <div className="flex items-start justify-between">
            <div>
              <h1 className="text-2xl font-bold text-awvs-text-primary mb-2">{selectedScenario.name}</h1>
              <div className="flex items-center gap-3">
                <span className={`px-3 py-1 rounded-full text-xs font-medium border ${VULN_TYPE_COLORS[selectedScenario.vuln_type] || 'bg-gray-100 text-gray-700 border-gray-200'}`}>
                  {VULN_TYPE_NAMES[selectedScenario.vuln_type] || selectedScenario.vuln_type}
                </span>
                <span className={`px-3 py-1 rounded-full text-xs font-medium border ${DIFFICULTY_COLORS[selectedScenario.difficulty] || 'bg-gray-100 text-gray-700 border-gray-200'}`}>
                  {DIFFICULTY_NAMES[selectedScenario.difficulty] || selectedScenario.difficulty}
                </span>
              </div>
            </div>
          </div>

          {selectedScenario.description && (
            <p className="text-awvs-text-secondary mt-4">{selectedScenario.description}</p>
          )}
        </div>

        {/* Tab 切换 */}
        <div className="flex gap-1 mb-6 bg-awvs-bg-light rounded-lg p-1 border border-awvs-border">
          <button
            onClick={() => setActiveTab('attack')}
            className={`px-4 py-2 rounded-md text-sm font-medium transition-colors ${
              activeTab === 'attack'
                ? 'bg-awvs-primary text-white'
                : 'text-awvs-text-secondary hover:text-awvs-text-primary'
            }`}
          >
             攻击演示
          </button>
          <button
            onClick={() => setActiveTab('remediation')}
            className={`px-4 py-2 rounded-md text-sm font-medium transition-colors ${
              activeTab === 'remediation'
                ? 'bg-awvs-primary text-white'
                : 'text-awvs-text-secondary hover:text-awvs-text-primary'
            }`}
          >
             修复方案
          </button>
          <button
            onClick={() => setActiveTab('learning')}
            className={`px-4 py-2 rounded-md text-sm font-medium transition-colors ${
              activeTab === 'learning'
                ? 'bg-awvs-primary text-white'
                : 'text-awvs-text-secondary hover:text-awvs-text-primary'
            }`}
          >
             原理讲解
          </button>
        </div>

        {/* 攻击演示 Tab */}
        {activeTab === 'attack' && (
          <div className="bg-white rounded-xl p-6 border border-awvs-border shadow-sm">
            {selectedScenario.attack_steps && selectedScenario.attack_steps.length > 0 ? (
              <>
                {/* 步骤导航 */}
                <div className="flex items-center gap-2 mb-6 overflow-x-auto pb-2">
                  {selectedScenario.attack_steps.map((step, index) => (
                    <button
                      key={index}
                      onClick={() => setCurrentStep(index)}
                      className={`flex-shrink-0 px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                        currentStep === index
                          ? 'bg-awvs-primary text-white'
                          : 'bg-awvs-bg-light text-awvs-text-secondary hover:bg-awvs-border'
                      }`}
                    >
                      Step {step.step}: {step.title}
                    </button>
                  ))}
                </div>

                {/* 当前步骤内容 */}
                {(() => {
                  const step = selectedScenario.attack_steps[currentStep];
                  return (
                    <div className="space-y-6">
                      {/* 步骤描述 */}
                      {step.description && (
                        <div className="bg-awvs-bg-light rounded-lg p-4 border border-awvs-border">
                          <h3 className="text-sm font-medium text-awvs-text-secondary mb-2">步骤说明</h3>
                          <p className="text-awvs-text-primary">{step.description}</p>
                        </div>
                      )}

                      {/* HTTP 请求 */}
                      {step.request && (
                        <div className="bg-awvs-bg-light rounded-lg p-4 border border-awvs-border">
                          <h3 className="text-sm font-medium text-awvs-text-secondary mb-2"> HTTP 请求</h3>
                          <pre className="text-sm text-green-600 overflow-x-auto whitespace-pre-wrap bg-white p-3 rounded border border-awvs-border">
                            {typeof step.request === 'object'
                              ? JSON.stringify(step.request, null, 2)
                              : String(step.request)}
                          </pre>
                        </div>
                      )}

                      {/* Payload */}
                      {step.payload && (
                        <div className="bg-red-50 rounded-lg p-4 border border-red-200">
                          <h3 className="text-sm font-medium text-red-600 mb-2"> 恶意 Payload</h3>
                          <code className="text-sm text-red-700 block bg-white p-3 rounded border border-red-200 overflow-x-auto">
                            {step.payload}
                          </code>
                          {step.payload_explanation && (
                            <p className="text-sm text-awvs-text-secondary mt-3">{step.payload_explanation}</p>
                          )}
                        </div>
                      )}

                      {/* HTTP 响应 */}
                      {step.response && (
                        <div className="bg-awvs-bg-light rounded-lg p-4 border border-awvs-border">
                          <h3 className="text-sm font-medium text-awvs-text-secondary mb-2"> HTTP 响应</h3>
                          <pre className="text-sm text-blue-600 overflow-x-auto whitespace-pre-wrap bg-white p-3 rounded border border-awvs-border">
                            {typeof step.response === 'object'
                              ? JSON.stringify(step.response, null, 2)
                              : String(step.response)}
                          </pre>
                        </div>
                      )}

                      {/* 执行结果 */}
                      {step.result && (
                        <div className="bg-green-50 border border-green-200 rounded-lg p-4">
                          <h3 className="text-sm font-medium text-green-600 mb-2"> 攻击结果</h3>
                          <p className="text-green-700">{step.result}</p>
                        </div>
                      )}

                      {/* 导航按钮 */}
                      <div className="flex justify-between pt-4">
                        <button
                          onClick={() => setCurrentStep(Math.max(0, currentStep - 1))}
                          disabled={currentStep === 0}
                          className="px-4 py-2 bg-awvs-bg-light text-awvs-text-secondary rounded-lg hover:bg-awvs-border disabled:opacity-50 disabled:cursor-not-allowed transition-colors border border-awvs-border"
                        >
                          ← 上一步
                        </button>
                        <button
                          onClick={() => setCurrentStep(Math.min(selectedScenario.attack_steps.length - 1, currentStep + 1))}
                          disabled={currentStep === selectedScenario.attack_steps.length - 1}
                          className="px-4 py-2 bg-awvs-primary text-white rounded-lg hover:bg-awvs-primary-hover disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                        >
                          下一步 →
                        </button>
                      </div>
                    </div>
                  );
                })()}
              </>
            ) : (
              <div className="text-center py-12 text-awvs-text-muted">
                暂无攻击演示数据
              </div>
            )}
          </div>
        )}

        {/* 修复方案 Tab */}
        {activeTab === 'remediation' && (
          <div className="space-y-4">
            {selectedScenario.remediation && selectedScenario.remediation.length > 0 ? (
              selectedScenario.remediation.map((item, index) => (
                <div key={index} className="bg-white rounded-xl p-6 border border-awvs-border shadow-sm">
                  <h3 className="text-lg font-medium text-awvs-text-primary mb-3">{item.title}</h3>
                  {item.description && (
                    <p className="text-awvs-text-secondary mb-4">{item.description}</p>
                  )}
                  {item.code && (
                    <pre className="bg-awvs-bg-light rounded-lg p-4 overflow-x-auto border border-awvs-border">
                      <code className="text-sm text-green-600">{item.code}</code>
                    </pre>
                  )}
                </div>
              ))
            ) : (
              <div className="bg-white rounded-xl p-12 text-center text-awvs-text-muted border border-awvs-border shadow-sm">
                暂无修复方案
              </div>
            )}
          </div>
        )}

        {/* 原理讲解 Tab */}
        {activeTab === 'learning' && (
          <div className="bg-white rounded-xl p-6 border border-awvs-border shadow-sm">
            {selectedScenario.learning ? (
              <div className="space-y-6">
                {/* 漏洞原理 */}
                {selectedScenario.learning.principle && (
                  <div>
                    <h3 className="text-lg font-medium text-awvs-text-primary mb-3"> 漏洞原理</h3>
                    <p className="text-awvs-text-secondary whitespace-pre-wrap">{selectedScenario.learning.principle}</p>
                  </div>
                )}

                {/* CWE/OWASP 分类 */}
                <div className="flex gap-4">
                  {selectedScenario.learning.cwe && (
                    <div className="bg-awvs-bg-light rounded-lg px-4 py-3 border border-awvs-border">
                      <span className="text-awvs-text-muted text-sm">CWE: </span>
                      <span className="text-blue-600 font-mono">{selectedScenario.learning.cwe}</span>
                    </div>
                  )}
                  {selectedScenario.learning.owasp && (
                    <div className="bg-awvs-bg-light rounded-lg px-4 py-3 border border-awvs-border">
                      <span className="text-awvs-text-muted text-sm">OWASP: </span>
                      <span className="text-awvs-primary font-mono">{selectedScenario.learning.owasp}</span>
                    </div>
                  )}
                </div>

                {/* 影响 */}
                {selectedScenario.learning.impact && (
                  <div>
                    <h3 className="text-lg font-medium text-awvs-text-primary mb-3"> 安全影响</h3>
                    <p className="text-awvs-text-secondary">{selectedScenario.learning.impact}</p>
                  </div>
                )}

                {/* 参考资料 */}
                {selectedScenario.learning.references && selectedScenario.learning.references.length > 0 && (
                  <div>
                    <h3 className="text-lg font-medium text-awvs-text-primary mb-3"> 参考资料</h3>
                    <ul className="space-y-2">
                      {selectedScenario.learning.references.map((ref, index) => (
                        <li key={index}>
                          <a
                            href={ref}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-blue-600 hover:text-blue-700 transition-colors"
                          >
                            {ref}
                          </a>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            ) : (
              <div className="text-center py-12 text-awvs-text-muted">
                暂无学习资料
              </div>
            )}
          </div>
        )}
      </div>
    );
  }

  // 场景列表视图
  return (
    <div className="p-6">
      {/* 标题 */}
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-awvs-text-primary flex items-center gap-3">
          <span className="text-3xl"></span>
          漏洞实验室
        </h1>
        <p className="text-awvs-text-secondary mt-2">
          通过模拟攻击过程，深入了解各类Web漏洞的原理、利用方式和修复方法
        </p>
      </div>

      {/* 筛选区域 */}
      <div className="bg-white rounded-xl p-4 mb-6 border border-awvs-border shadow-sm">
        <div className="flex flex-wrap items-center gap-4">
          {/* 搜索框 */}
          <div className="flex-1 min-w-[200px]">
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="搜索场景名称或描述..."
              className="w-full bg-awvs-bg-light border border-awvs-border rounded-lg px-4 py-2 text-awvs-text-primary placeholder-awvs-text-muted focus:outline-none focus:border-awvs-primary focus:ring-2 focus:ring-awvs-primary/20 transition-all"
            />
          </div>

          {/* 漏洞类型筛选 */}
          <select
            value={selectedType || ''}
            onChange={(e) => setSelectedType(e.target.value || null)}
            className="bg-awvs-bg-light border border-awvs-border rounded-lg px-4 py-2 text-awvs-text-primary focus:outline-none focus:border-awvs-primary focus:ring-2 focus:ring-awvs-primary/20 transition-all"
          >
            <option value="">所有漏洞类型</option>
            {vulnTypes.map((type) => (
              <option key={type.code} value={type.code}>
                {type.name} ({type.count})
              </option>
            ))}
          </select>

          {/* 难度筛选 */}
          <select
            value={selectedDifficulty || ''}
            onChange={(e) => setSelectedDifficulty(e.target.value || null)}
            className="bg-awvs-bg-light border border-awvs-border rounded-lg px-4 py-2 text-awvs-text-primary focus:outline-none focus:border-awvs-primary focus:ring-2 focus:ring-awvs-primary/20 transition-all"
          >
            <option value="">所有难度</option>
            <option value="easy">初级</option>
            <option value="medium">中级</option>
            <option value="hard">高级</option>
          </select>

          {/* 重置按钮 */}
          {(selectedType || selectedDifficulty || searchQuery || showAutoGenerated !== null) && (
            <button
              onClick={handleResetFilters}
              className="px-3 py-2 text-awvs-text-secondary hover:text-awvs-primary transition-colors rounded-lg hover:bg-awvs-bg-light"
            >
              清除筛选
            </button>
          )}

          {/* 自动生成筛选 */}
          <select
            value={showAutoGenerated === null ? 'all' : showAutoGenerated ? 'auto' : 'manual'}
            onChange={(e) => setShowAutoGenerated(
              e.target.value === 'all' ? null : e.target.value === 'auto' ? true : false
            )}
            className="bg-awvs-bg-light border border-awvs-border rounded-lg px-4 py-2 text-awvs-text-primary focus:outline-none focus:border-awvs-primary focus:ring-2 focus:ring-awvs-primary/20 transition-all"
          >
            <option value="all">全部来源</option>
            <option value="auto">自动生成</option>
            <option value="manual">手动创建</option>
          </select>
        </div>
      </div>

      {/* 场景列表 */}
      {loading ? (
        <div className="flex items-center justify-center py-12">
          <div className="w-8 h-8 border-2 border-awvs-primary/30 border-t-awvs-primary rounded-full animate-spin"></div>
        </div>
      ) : scenarios.length === 0 ? (
        <div className="bg-white rounded-xl p-12 text-center border border-awvs-border shadow-sm">
          <p className="text-awvs-text-muted">暂无漏洞场景数据</p>
          <p className="text-awvs-text-secondary text-sm mt-2">请先在数据库中添加场景数据</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {scenarios
            .filter((scenario) => {
              if (showAutoGenerated === null) return true;
              return (scenario.is_auto_generated || false) === showAutoGenerated;
            })
            .map((scenario) => (
            <div
              key={scenario.id}
              onClick={() => setSelectedScenario(scenario)}
              className="bg-white rounded-xl p-5 cursor-pointer hover:shadow-md transition-all border border-awvs-border hover:border-awvs-primary/30 shadow-sm"
            >
              <div className="flex items-start justify-between mb-3">
                <div className="flex items-start gap-2 flex-1">
                  <h3 className="text-awvs-text-primary font-medium flex-1">{scenario.name}</h3>
                  {scenario.is_auto_generated && (
                    <span className="px-2 py-0.5 rounded text-xs font-medium border bg-purple-50 text-purple-700 border-purple-200 flex-shrink-0">
                      自动生成
                    </span>
                  )}
                </div>
                <span className={`px-2 py-0.5 rounded text-xs font-medium border ml-2 ${DIFFICULTY_COLORS[scenario.difficulty]}`}>
                  {DIFFICULTY_NAMES[scenario.difficulty]}
                </span>
              </div>
              
              <div className="mb-3">
                <span className={`px-2 py-0.5 rounded text-xs border ${VULN_TYPE_COLORS[scenario.vuln_type] || 'bg-gray-100 text-gray-700 border-gray-200'}`}>
                  {VULN_TYPE_NAMES[scenario.vuln_type] || scenario.vuln_type}
                </span>
              </div>

              {scenario.description && (
                <p className="text-awvs-text-secondary text-sm line-clamp-2">{scenario.description}</p>
              )}

              <div className="flex items-center gap-2 mt-4 text-xs text-awvs-text-muted">
                <span>{scenario.attack_steps?.length || 0} 个攻击步骤</span>
                <span>•</span>
                <span>{scenario.remediation?.length || 0} 个修复方案</span>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default LabHome;
