# Generated by Django 6.0 on 2025-12-06 14:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(help_text='任务唯一标识符', max_length=50, unique=True)),
                ('task_name', models.CharField(blank=True, help_text='任务名称，可选', max_length=200, null=True)),
                ('target_url', models.URLField(help_text='目标Web应用的完整URL', max_length=500)),
                ('status', models.CharField(choices=[('queued', '等待执行'), ('running', '执行中'), ('paused', '已暂停'), ('completed', '已完成'), ('failed', '执行失败'), ('cancelled', '已取消')], default='queued', help_text='任务当前状态', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='扫描进度百分比 (0-100)')),
                ('scan_profile', models.CharField(choices=[('quick', '快速扫描'), ('full', '完整扫描'), ('custom', '自定义扫描')], default='full', help_text='扫描配置模板', max_length=20)),
                ('custom_modules', models.JSONField(blank=True, help_text='自定义启用的检测模块列表', null=True)),
                ('auth_token', models.TextField(blank=True, help_text='用于认证的会话Token', null=True)),
                ('auth_cookies', models.TextField(blank=True, help_text='用于认证的Cookie字符串', null=True)),
                ('max_depth', models.IntegerField(default=5, help_text='爬虫最大深度 (1-10)')),
                ('max_pages', models.IntegerField(default=100, help_text='最大扫描页面数 (10-1000)')),
                ('timeout', models.IntegerField(default=30, help_text='请求超时时间(秒)')),
                ('user_agent', models.TextField(blank=True, help_text='自定义User-Agent', null=True)),
                ('headers', models.JSONField(blank=True, help_text='自定义HTTP请求头', null=True)),
                ('exclude_patterns', models.JSONField(blank=True, help_text='排除的URL模式(正则表达式)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='任务创建时间')),
                ('started_at', models.DateTimeField(blank=True, help_text='任务开始执行时间', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='任务完成时间', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新时间')),
                ('pages_scanned', models.IntegerField(default=0, help_text='已扫描页面数')),
                ('vulnerabilities_found', models.IntegerField(default=0, help_text='发现的漏洞总数')),
                ('created_by', models.ForeignKey(help_text='任务创建者', on_delete=django.db.models.deletion.CASCADE, related_name='scan_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '扫描任务',
                'verbose_name_plural': '扫描任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_stack', models.JSONField(blank=True, help_text='识别出的技术栈信息', null=True)),
                ('summary', models.JSONField(default=dict, help_text='扫描结果统计摘要')),
                ('report_data', models.JSONField(blank=True, help_text='完整的扫描报告数据', null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='报告生成时间')),
                ('task', models.OneToOneField(help_text='关联的扫描任务', on_delete=django.db.models.deletion.CASCADE, related_name='result', to='scans.scantask')),
            ],
            options={
                'verbose_name': '扫描结果',
                'verbose_name_plural': '扫描结果',
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', '调试'), ('INFO', '信息'), ('WARNING', '警告'), ('ERROR', '错误'), ('CRITICAL', '严重')], default='INFO', help_text='日志级别', max_length=10)),
                ('message', models.TextField(help_text='日志消息')),
                ('module', models.CharField(blank=True, help_text='产生日志的模块', max_length=100, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='日志时间戳')),
                ('extra_data', models.JSONField(blank=True, help_text='额外的日志数据', null=True)),
                ('task', models.ForeignKey(help_text='关联的扫描任务', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scans.scantask')),
            ],
            options={
                'verbose_name': '扫描日志',
                'verbose_name_plural': '扫描日志',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerability_id', models.CharField(help_text='漏洞唯一标识符', max_length=50, unique=True)),
                ('name', models.CharField(help_text='漏洞名称', max_length=200)),
                ('type', models.CharField(help_text='漏洞类型', max_length=100)),
                ('url', models.URLField(help_text='漏洞发现URL', max_length=500)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS'), ('PATCH', 'PATCH')], default='GET', help_text='HTTP请求方法', max_length=10)),
                ('parameter', models.CharField(blank=True, help_text='涉及的参数名', max_length=200, null=True)),
                ('payload', models.TextField(blank=True, help_text='攻击载荷', null=True)),
                ('evidence', models.TextField(blank=True, help_text='漏洞证据', null=True)),
                ('cvss_score', models.FloatField(default=0.0, help_text='CVSS评分 (0.0-10.0)')),
                ('cvss_vector', models.CharField(blank=True, help_text='CVSS向量字符串', max_length=200, null=True)),
                ('risk_level', models.CharField(choices=[('info', '信息'), ('low', '低危'), ('medium', '中危'), ('high', '高危'), ('critical', '危急')], default='info', help_text='风险等级', max_length=20)),
                ('description', models.TextField(blank=True, help_text='漏洞详细描述', null=True)),
                ('remediation', models.TextField(blank=True, help_text='修复建议', null=True)),
                ('references', models.JSONField(blank=True, help_text='参考链接列表', null=True)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now, help_text='漏洞检测时间')),
                ('attack_steps', models.JSONField(blank=True, help_text='攻击过程步骤记录', null=True)),
                ('screenshots', models.JSONField(blank=True, help_text='截图文件信息', null=True)),
                ('task', models.ForeignKey(help_text='关联的扫描任务', on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scans.scantask')),
            ],
            options={
                'verbose_name': '漏洞',
                'verbose_name_plural': '漏洞',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scantask',
            index=models.Index(fields=['task_id'], name='scans_scant_task_id_6cae4a_idx'),
        ),
        migrations.AddIndex(
            model_name='scantask',
            index=models.Index(fields=['status'], name='scans_scant_status_3b4b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='scantask',
            index=models.Index(fields=['created_by'], name='scans_scant_created_463807_idx'),
        ),
        migrations.AddIndex(
            model_name='scantask',
            index=models.Index(fields=['created_at'], name='scans_scant_created_908f19_idx'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['task'], name='scans_scanr_task_id_a39bbb_idx'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['generated_at'], name='scans_scanr_generat_af018b_idx'),
        ),
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['task'], name='scans_scanl_task_id_0ced2d_idx'),
        ),
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['level'], name='scans_scanl_level_5fd5d1_idx'),
        ),
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['timestamp'], name='scans_scanl_timesta_e6cd0d_idx'),
        ),
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['module'], name='scans_scanl_module_52003c_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['vulnerability_id'], name='scans_vulne_vulnera_8eef74_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['task'], name='scans_vulne_task_id_b3ec40_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['type'], name='scans_vulne_type_434ee9_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['risk_level'], name='scans_vulne_risk_le_ef6ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['cvss_score'], name='scans_vulne_cvss_sc_3a9be7_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['detected_at'], name='scans_vulne_detecte_02172e_idx'),
        ),
    ]
